user                        nginx;
worker_processes            2;

error_log                   /var/log/nginx/error.log crit;
pid                         /var/run/nginx.pid;
worker_rlimit_nofile        20000;

events {
    worker_connections      4096;
    use                     epoll;
    multi_accept            on;
}

http {
    include                 /etc/nginx/mime.types;
    include                 /etc/nginx/proxy.conf;
    default_type            application/octet-stream;

    log_format              main_format     '$time_local | $remote_addr | [$status] "$request" ( Req: $request_time || Res: $upstream_response_time ) "$http_user_agent" "$http_referer" "$http_x_forwarded_for"';
#    access_log              /dev/stdout     main_format;
    access_log              off;

    gzip                    on;
    gzip_vary               on;
    gzip_static             on;
    gzip_comp_level         9;
    gzip_buffers            16   16k;
    gzip_min_length         0;
    gzip_disable            "msie6";
    gzip_types              text/plain text/css application/json text/javascript application/javascript application/x-javascript text/xml application/xml application/xml+rss application/msgpack;
    gzip_proxied            any;
    gzip_http_version       1.1;

    keepalive_timeout       30;
    keepalive_requests      1000;

    client_body_buffer_size     10k;
    client_header_buffer_size   1k;
    client_max_body_size        8m;
    large_client_header_buffers 4   32k;

    client_body_timeout         10;
    client_header_timeout       10;
    reset_timedout_connection   on;

    send_timeout                2;

    #open_file_cache             max=200000 inactive=20s;
    #open_file_cache_valid       30s;
    #open_file_cache_min_uses    2;
    #open_file_cache_errors      on;

    sendfile                    on;
    tcp_nopush                  on;
    tcp_nodelay                 on;

    include                 /etc/nginx/conf.d/*.conf;
}