import {DASHBOARD_SERVICE_ROOT_PATH} from '@packages/dashboardService/pages/constants/rootPath'

export const DASHBOARD_SERVICE_CUSTOM_INFO_PATH_PATH = `${DASHBOARD_SERVICE_ROOT_PATH}custom-page`
export const DASHBOARD_SERVICE_DASHBOARD_SERVICE_CUSTOM_INFO_PATH_PATH_WIDTH_KEY = `${DASHBOARD_SERVICE_CUSTOM_INFO_PATH_PATH}/:pagePath`
