export interface User{
    address: null,
    birthdate: string,
    email: string,
    email_verified: boolean,
    family_name: string,
    gender: string,
    given_name: string,
    id: number,
    open_id: number,
    locale: string,
    middle_name: string,
    name: string,
    nickname: null,
    phone_number: string,
    phone_number_verified: boolean,
    picture: string,
    preferred_username: null,
    profile: null,
    sub: string,
    updated_at: number
    website: null | string,
    zoneinfo: string,
}
